version: '3.9'

services:
  {{ project_name }}:
    build: .
    container_name: {{ project_name }}
    restart: always
    networks:
      - {{ shared_network }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ project_name }}.rule=Host(`{{ domain }}`)"
      - "traefik.http.routers.{{ project_name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}.tls.certresolver=mytls"
      - "traefik.http.services.{{ project_name }}.loadbalancer.server.port=80"
      {% if redirect_www %}
      - "traefik.http.routers.{{ project_name }}-www.rule=Host(`www.{{ domain }}`)"
      - "traefik.http.routers.{{ project_name }}-www.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}-www.tls.certresolver=mytls"
      - "traefik.http.routers.{{ project_name }}-www.middlewares={{ project_name }}-redirect"
      - "traefik.http.middlewares.{{ project_name }}-redirect.redirectregex.regex=^https://www\\.(.*)"
      - "traefik.http.middlewares.{{ project_name }}-redirect.redirectregex.replacement=https://$${1}"
      {% endif %}

networks:
  {{ shared_network }}:
    external: true
