version: '3.8'

services:
  ubuntu-shell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-shell
    hostname: ubuntu-shell
    restart: unless-stopped
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
