version: '3.9'

services:
  {{ project_name }}:
    build: .
    container_name: {{ project_name }}
    restart: always
    environment:
      - APP_NAME={{ app_name }}
      - APP_ENV={{ app_env }}
      - APP_KEY={{ app_key }}
      - APP_DEBUG={{ app_debug }}
      - APP_URL={{ app_url }}
      - DB_CONNECTION=mysql
      - DB_HOST={{ shared_mysql_container }}
      - DB_PORT=3306
      - DB_DATABASE={{ db_name }}
      - DB_USERNAME={{ db_user }}
      - DB_PASSWORD={{ db_password }}
      - REDIS_HOST={{ shared_redis_container }}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - {{ shared_network }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ project_name }}.rule=Host(`{{ domain }}`)"
      - "traefik.http.routers.{{ project_name }}.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}.tls.certresolver=mytls"
      - "traefik.http.services.{{ project_name }}.loadbalancer.server.port=80"
      {% if redirect_www %}
      - "traefik.http.routers.{{ project_name }}-www.rule=Host(`www.{{ domain }}`)"
      - "traefik.http.routers.{{ project_name }}-www.entrypoints=websecure"
      - "traefik.http.routers.{{ project_name }}-www.tls.certresolver=mytls"
      - "traefik.http.routers.{{ project_name }}-www.middlewares={{ project_name }}-redirect"
      - "traefik.http.middlewares.{{ project_name }}-redirect.redirectregex.regex=^https://www\\.(.*)"
      - "traefik.http.middlewares.{{ project_name }}-redirect.redirectregex.replacement=https://$${1}"
      {% endif %}

networks:
  {{ shared_network }}:
    external: true
